### ISSUE TITLE
Feature Request: Apply to span tags

### ISSUE THREAD

**Issue by sebszocinski** [jacksleight/bard-paragraph-style#3]
Not sure if this is possible or not and I tried to do it once with Redactor and it didn't end well, but I'm curious to see if this would work with span tags so you could style inline elements?

**Comment by jacksleight** [comment]
I've just released a new addon that is a replacement for this one and supports span tags (as well as headings): https://github.com/jacksleight/statamic-bard-texstyle

Migration is as simple as possible, there's a guide in the docs.
