### ISSUE TITLE
Can't move the buttons in the toolbar

### ISSUE THREAD

**Issue by twd3** [jacksleight/bard-paragraph-style#6]
I just tried moving the buttons in the toolbar and I can't get them to move, they stay to the right heading buttons no matter where I move them?

**Comment by jacksleight** [comment]
Ah yeah good point.

I'm probably not going to change this in this addon as the buttons have always been in a fixed position after the header buttons, and alterting it now would move them around for everyone when they update. There's also another BC issue as the earlier versions of this addon didn't let you manage the buttons at all (they were always added to every Bard) so in that situation the buttons have no positon data at all.

However! I will very shortly be releasing a replacement for this addon: https://github.com/jacksleight/statamic-bard-texstyle

It uses Statamic's new button managament features, and I will implement the user ordering as well. Migration to this new addon is going to be really straightforward.

I'll leave a comment here when it's out, should be today or tomorrow.

**Comment by twd3** [comment]
Wow, so awesome! It wouldn't even be that big of a deal to live with the buttons where they are but now I'm looking forward to this new addon!
